apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: app
        emptyDir: {}
      containers: 
      - name: caddy
        image:  kibomibo/otus-kube:homework1
        volumeMounts:
        - name: app
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000                                 
        livenessProbe:
          tcpSocket:  {port: 8000}
      initContainers:
      - name: uploader
        image: busybox:1.31.0
        command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
        volumeMounts:
        - name: app
          mountPath: /app
