apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  volumes:
    - name: storage-pvc
      persistentVolumeClaim:
        claimName: storage-pvc
  containers:
    - name: storage-container
      image: nginx
      volumeMounts:
        - name: storage-pvc
          mountPath: /data
