apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-monitoring
  labels:
    app: kube-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-monitoring
  template:
    metadata:
      labels:
        app: kube-monitoring
    spec:
      volumes:
        - name: nginx-configs
          configMap:
            name: nginx-cm 
      containers:
      - name: nginx-a
        image: nginx:1.23-alpine
        ports:
        - name: http
          containerPort: 8085
        volumeMounts:
          - name: nginx-configs
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      - name: exporter-nginx
        image: nginx/nginx-prometheus-exporter:0.9.0
        command:
        - "/usr/bin/nginx-prometheus-exporter"
        - "-nginx.scrape-uri=http://127.0.0.1:8080/basic_status"
        ports:
        - name: http-metrics
          containerPort: 9113
