apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  default.conf: |-
      server {
        listen 8085 default_server;
        server_name _;
        charset utf-8;

        location / {
          add_header Content-Type text/plain;
          return 200 "HELLO";
        }
      }
      server {
        listen 8080 default_server;
        server_name _;
        location = /basic_status {
          stub_status;
        }
      }
