apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor
metadata:
  name: example-app 
  labels:
    team: frontend 
spec:
  selector: 
    matchLabels:
      app: kube-monitoring
  endpoints:
  - port: http
