apiVersion: apps/v1 
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    rollingUpdate:
      maxUnavailable: "1%"
      maxSurge: 1
  template:
    metadata: 
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: kibomibo/otus-microservice-payment:v0.0.2
        env:
        - name: PORT
          value: "3333"
        - name: DISABLE_PROFILER
          value: "1"
