apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  incressClass: nginx
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: http
