apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server 
spec:
  volumes:
  - name: app
    emptyDir: {}
  containers: 
  - name: caddy
    image:  kibomibo/otus-kube:homework1
    volumeMounts:
    - name: app
      mountPath: /app
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80                                 
    livenessProbe:
      tcpSocket:  {port: 8000}
  initContainers:
  - name: uploader
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
    
